import type { LegalBlock } from "@/components/legal-document";

export const INTEREST_RATE_POLICY_BLOCKS: LegalBlock[] = [
  { type: "title", text: "Interest Rate Policy" },
  { type: "meta", text: "Yellow Metal Loans Private Limited · Version 1/2026-27 · Effective 08 June 2026 · Reviewed annually" },
  { type: "h2", text: "Background" },
  { type: "p", text: "Yellow Metal Loans Private Limited (hereinafter referred to as \"Yellow Metal Loans\" or \"the Company\") is registered with the Reserve Bank of India as a Non-Banking Financial Company, Not Deposit-Taking, Credit and Investment Company (\"NBFC-ND-ICC\") and incorporated under the provisions of the Companies Act, 2013." },
  { type: "p", text: "The Company is primarily engaged in providing loans against eligible gold ornaments and jewellery pledged as collateral (“Gold Loans”), through a branch-based, in-person lending model. The Company may, from time to time, also offer other lending products as approved by the Board of Directors and permitted under applicable RBI regulations." },
  { type: "p", text: "As per the Master Direction – Reserve Bank of India (Non-Banking Financial Companies – Responsible Business Conduct) Directions, 2025 (\"RBI Directions\"), all NBFCs are required to lay out appropriate internal principles and procedures for determining interest rates and other charges levied on borrowers. This Policy has been formulated in compliance with such requirements." },
  { type: "h2", text: "Regulatory Framework" },
  { type: "p", text: "This Policy is framed in accordance with the following regulatory directions, as amended from time to time:" },
  { type: "p", text: "Master Direction – Reserve Bank of India (Non-Banking Financial Companies – Responsible Business Conduct) Directions, 2025" },
  { type: "p", text: "Master Direction – Reserve Bank of India (Non-Banking Financial Companies – Credit Facilities) Directions, 2025" },
  { type: "p", text: "Reserve Bank of India (Non-Banking Financial Companies – Credit Facilities) Directions, 2025" },
  { type: "p", text: "Any other RBI master directions, circulars, or guidelines applicable to the Company from time to time" },
  { type: "p", text: "In the event of any conflict between this Policy and applicable RBI regulations or law, the applicable RBI regulations or law shall prevail. This Policy shall be updated within 30 days of any material change in applicable regulation." },
  { type: "h2", text: "Effective Date and Applicability" },
  { type: "p", text: "This Policy shall be effective from June 08, 2026" },
  { type: "p", text: "This Policy applies to:" },
  { type: "p", text: "All Gold Loan products offered by the Company." },
  { type: "p", text: "Any other lending products that the Company may offer from time to time." },
  { type: "p", text: "All branches, offices, and employees involved in loan origination, pricing, and disbursement." },
  { type: "p", text: "Any changes to this Policy require approval of the Board of Directors." },
  { type: "h2", text: "Key Definitions" },
  { type: "p", text: "Unless otherwise defined, the following terms shall have the meanings set out below:" },
  { type: "p", text: "Applicable Gold Price — Lower of: (a) the 30-day average closing price of 22-carat gold, and (b) the previous business day's closing price, as published by a recognized commodity exchange or association accepted by the RBI." },
  { type: "p", text: "Bullet Repayment Loan — A Gold Loan where the principal and accrued interest are repaid in a single instalment at the end of the loan tenure. Maximum permitted tenure: 12 months." },
  { type: "p", text: "Key Facts Statement (KFS) — The standardized document prescribed by the RBI summarizing all key loan terms, delivered digitally (via WhatsApp/SMS) and/or in physical form at or before disbursement." },
  { type: "p", text: "LTV Ratio — Loan-to-Value Ratio: the ratio of the loan amount to the Standard Gold Value of pledged collateral, computed per RBI guidelines." },
  { type: "p", text: "Monthly Plan — A Gold Loan Scheme where the borrower pays interest on a monthly basis  with principal repayable at the end of the term." },
  { type: "p", text: "Net Disbursement — The actual amount credited to the borrower's bank account = Sanctioned Loan Amount minus applicable stamp duties, processing fees, and other deductions disclosed in the KFS." },
  { type: "p", text: "Penal Charges — Additional charges levied on overdue amounts (distinct from interest); shall not be compounded." },
  { type: "p", text: "Risk Management Committee (RMC) — The committee constituted by the Board of Directors responsible for risk oversight, pricing decisions, and interest rate approvals in the Company." },
  { type: "p", text: "Scheme — A defined Gold Loan product with specific LTV band, tenure range, repayment structure, tenure-slab rate grid, and applicable fees as approved by the Board/RMC." },
  { type: "p", text: "Standard Gold Value — Value of pledged gold = 22-carat equivalent weight × Applicable Gold Price. Basis for LTV computation." },
  { type: "p", text: "Step-Up Rate — A rate structure where the applicable interest rate increases as the loan ages beyond defined tenure slabs (e.g., lower rate for 0–30 days, higher for 31–180 days), incentivising early repayment." },
  { type: "p", text: "Tenure Slab — A defined period within the maximum loan tenure for which a specific interest rate applies under a Step-Up Rate structure." },
  { type: "h2", text: "Objectives of the Policy" },
  { type: "p", text: "The objectives of this Policy are to:" },
  { type: "p", text: "(a)  Establish a transparent, consistent, and risk-calibrated methodology for determining interest rates on all Gold Loan products." },
  { type: "p", text: "(b)  Ensure full compliance with RBI guidelines on fair and transparent pricing, borrower protection, and the Key Facts Statement (KFS) framework." },
  { type: "p", text: "(c)  Define a Scheme-Based, Step-Up Interest Rate Model linked to LTV ratios, loan tenure slabs, repayment structure, and borrower profile." },
  { type: "p", text: "(d)  Ensure that the rate of interest, tenure-slab rate grid, and rationale for differential pricing are clearly communicated to borrowers in the Sanction Letter and KFS." },
  { type: "p", text: "(e)  Maintain the Company's financial viability by factoring in cost of funds, credit risk premium, operating costs, and required margin." },
  { type: "p", text: "(f)  Ensure that interest rates are fair, objective, and free from discrimination across all borrower segments." },
  { type: "h2", text: "Governance and Oversight" },
  { type: "h3", text: "Board of Directors" },
  { type: "p", text: "The Board of Directors shall:" },
  { type: "p", text: "Approve this Policy and all material amendments thereto." },
  { type: "p", text: "Set the overall interest rate philosophy, acceptable rate bands for each product category, and risk-return expectations." },
  { type: "p", text: "Ratify RMC decisions on interest rate changes at each Board meeting." },
  { type: "p", text: "Ensure the interest rate framework is consistent with the Company's risk appetite, regulatory obligations, and borrower protection principles." },
  { type: "h3", text: "Risk Management Committee (RMC)" },
  { type: "p", text: "In addition to its risk oversight mandate, the RMC is designated to perform interest rate governance functions, including:" },
  { type: "p", text: "Approving specific Gold Loan Schemes and their associated interest rates and tenure-slab rate grids, within Board-approved range bands." },
  { type: "p", text: "Reviewing and approving changes to interest rates for all loan products at least quarterly, or as market or cost-of-funds conditions warrant." },
  { type: "p", text: "Monitoring the Company's cost of funds, gold price movements, and pricing competitiveness against peer gold loan NBFCs." },
  { type: "p", text: "Assessing interest rate risk and gold price sensitivity for any proposed new Scheme." },
  { type: "p", text: "Recommending risk-based pricing parameters and advising on LTV buffers required to remain compliant through the loan tenure." },
  { type: "p", text: "Placing all interest rate decisions before the Board for ratification at the next Board meeting." },
  { type: "p", text: "The RMC shall meet at least once a quarter to review interest rates and scheme performance. Its composition and charter shall be as prescribed in the Company's Risk Management Policy." },
  { type: "h3", text: "Operational Pricing Decisions" },
  { type: "p", text: "Within the Scheme framework approved by the Board/RMC, the Loan Manager or Branch Manager shall have the authority to:" },
  { type: "p", text: "Recommend the applicable Scheme for a borrower based on the LTV recorded at origination for the borrower and loan amount." },
  { type: "p", text: "Apply differential pricing within the approved Scheme rate band, based on objective criteria (LTV band, loan amount, and customer history)." },
  { type: "p", text: "The Loan Manager / Branch Manager shall not have authority to price outside the applicable Scheme band without prior RMC approval." },
  { type: "h2", text: "Interest Rate Model — Gold Loans" },
  { type: "h3", text: "General Principles" },
  { type: "p", text: "The Company follows a Scheme-Based, Step-Up Interest Rate Model for Gold Loans. Loans are offered under Board/RMC-approved Schemes. The rate applicable to a specific borrower is determined within the framework of the applicable Scheme based on: (a) the LTV chosen/assigned, (b) the repayment mode, and (c) the tenure slab rate grid applicable to that Scheme." },
  { type: "p", text: "All interest rates shall be expressed as annualized rates (% per annum) in all communications, sanction letters, and KFS documents." },
  { type: "h3", text: "Pricing Factors" },
  { type: "p", text: "The interest rate charged on Gold Loans shall be determined by:" },
  { type: "p", text: "Loan-to-Value (LTV) Ratio — Primary risk determinant. The LTV applicable to a loan is determined and recorded at origination based on the options made available under the applicable Scheme, within the permissible RBI cap for the loan segment. The Company may offer multiple internal LTV bands (e.g., lower, mid, and higher LTV options) within the RBI cap as part of its Scheme design. Lower LTV selection → lower rate; higher LTV selection → higher rate." },
  { type: "p", text: "Repayment Structure — Monthly Plan (interest-only monthly payments) or Bullet Repayment  — priced differently based on risk and RBI LTV-at-maturity requirements." },
  { type: "p", text: "Tenure Slab — Step-up rate structure: rates increase as the loan ages beyond defined tenure slab thresholds, incentivising early repayment by the borrower." },
  { type: "p", text: "Loan Amount (Ticket Size) — Rates vary across small-ticket (up to Rs. 2.5 lakh), mid-ticket (Rs. 2.5 lakh – Rs. 5 lakh), and large-ticket (above Rs. 5 lakh) segments, consistent with RBI LTV tiers." },
  { type: "p", text: "Loan Purpose — As declared by the borrower at origination." },
  { type: "p", text: "Gold Purity — Assessed at branch by a certified assayer. Higher purity provides stronger collateral; may support lower risk pricing within the same LTV band." },
  { type: "p", text: "Cost of Funds — The Company's weighted average cost of borrowings from banks, NBFCs, and other sources." },
  { type: "h3", text: "LTV-Based Tiered Rate Framework" },
  { type: "p", text: "In accordance with the RBI Gold Loan Circular, the Company shall observe the following tiered LTV caps and calibrate interest rates accordingly. Within each segment, the Company may structure loans at multiple LTV points. The LTV applicable to a specific loan is recorded at origination by the authorised branch official, subject to the following caps:" },
  { type: "p", text: "Up to Rs. 2.5 lakh: Max. LTV 85% of Standard Gold Value. Rate direction: Competitive / lower end. Targets rural/semi-urban segment; higher LTV allowed but smaller ticket limits concentrated risk." },
  { type: "p", text: "Rs. 2.5 lakh – Rs. 5 lakh: Max. LTV 80% of Standard Gold Value. Rate direction: Mid-range. Balanced ticket size with moderate LTV cap; standard retail gold lending segment." },
  { type: "p", text: "Above Rs. 5 lakh: Max. LTV 75% of Standard Gold Value. Rate direction: Higher end (near cap). Larger exposure; stricter LTV limit; rate reflects tighter margin buffer needed to stay LTV-compliant at maturity." },
  { type: "h3", text: "Step-Up Tenure-Slab Rate Structure" },
  { type: "p", text: "The Company employs a Step-Up Rate structure in its Gold Loan Schemes. Under this structure, the applicable interest rate increases (steps up) as the loan ages beyond defined tenure slab thresholds. This is designed to:" },
  { type: "p", text: "Incentivise borrowers to repay their loans within the initial (lower-rate) tenure slab." },
  { type: "p", text: "Reflect the increasing credit risk and gold price risk that accumulates as a loan remains outstanding over a longer period." },
  { type: "p", text: "Encourage portfolio churn and reduce long-duration gold custody risk at branches." },
  { type: "p", text: "Illustrative Scheme Rate Grid:" },
  { type: "p", text: "Monthly Plan (75% LTV) · 0 – 30 days · 13.00% p.a. · Rs. 1,083 per Rs. 1 lakh" },
  { type: "p", text: "Monthly Plan (75% LTV) · 31 – 180 days · 16.66% p.a. · Rs. 1,388 per Rs. 1 lakh" },
  { type: "p", text: "The Board/RMC shall approve all Scheme Rate Grids, including tenure slab breakpoints and applicable rates at each slab. The rate grid for each active Scheme shall be maintained in the Scheme Master and communicated to branches. Any revision to the rate grid requires RMC approval, with Board ratification at the next meeting." },
  { type: "h3", text: "Gold Valuation Basis for LTV Computation" },
  { type: "p", text: "The Standard Gold Value used for LTV computation shall be determined as follows:" },
  { type: "p", text: "(a)  All pledged gold ornaments/jewellery shall be assessed for purity by a certified in-house assayer at the branch. Each jewel item shall be recorded individually with: Net Weight, Gross Weight, and Purity (in carats). The assayer's valuation shall be captured digitally and attached to the loan record." },
  { type: "p", text: "(b)  The actual purity shall be converted to 22-carat equivalent: [22-carat equivalent weight = Actual Weight × (Actual Purity ÷ 22)]." },
  { type: "p", text: "(c)  Standard Gold Value = 22-carat equivalent weight × Applicable Gold Price, where Applicable Gold Price = lower of (i) 30-day average closing price of 22-carat gold, and (ii) previous business day's closing price." },
  { type: "p", text: "(d)  Loan amount disbursed shall not exceed the maximum LTV applicable to the loan segment, applied to the Standard Gold Value. The system shall display the eligible loan value based on this computation." },
  { type: "p", text: "(e)  Gold jewellery shall be tagged with a Packet Number at the branch for custody tracking throughout the loan tenure." },
  { type: "h3", text: "Repayment Structures and Rate Implications" },
  { type: "h3", text: "A.   Monthly Plan (Interest-Only Monthly Payments)" },
  { type: "p", text: "Borrower pays interest on a monthly basis; principal is repayable at the end of the tenure or on demand." },
  { type: "p", text: "The applicable rate for each billing month is determined by the Tenure Slab in which the loan falls at that point (Step-Up Rate applies)." },
  { type: "p", text: "Maximum tenure as per Scheme terms and RBI regulations; must not result in evergreening." },
  { type: "h3", text: "B.   Bullet Repayment Loans" },
  { type: "p", text: "Maximum tenure: 12 months from date of sanction." },
  { type: "p", text: "LTV shall be calculated on total repayment due at maturity (principal + total accrued interest at the applicable tenure-slab rates), not merely the disbursed amount." },
  { type: "p", text: "Compliance illustration: For a loan above Rs. 5 lakh at 17–18% p.a. (12-month bullet), the initial disbursement LTV should be ~63–64% so the aggregate LTV at maturity remains within the 75% cap." },
  { type: "p", text: "No rollover or renewal of a Bullet Repayment Loan shall be permitted unless accrued interest is fully repaid by the borrower at renewal." },
  { type: "p", text: "The LTV shall be monitored during the tenure; margin calls / partial repayment may be required if gold prices fall significantly." },
  { type: "h3", text: "Interest Rate Model — Other Lending Products" },
  { type: "p", text: "To the extent the Company offers lending products other than Gold Loans (as approved by the Board and permitted under applicable RBI regulations):" },
  { type: "p", text: "Interest rates shall be determined based on cost of funds, credit risk premium, product-specific risk factors, operating costs, and market benchmarks." },
  { type: "p", text: "The RMC shall define separate Scheme frameworks and rate bands for each product, approved by the Board before launch." },
  { type: "p", text: "All provisions of this Policy on KFS, borrower communication, transparency, and display requirements apply equally." },
  { type: "p", text: "For floating rate products (if introduced), rate resets shall follow RBI guidelines applicable to that product type; changes shall be communicated to borrowers in advance and shall not apply retrospectively." },
  { type: "h2", text: "Fee and Charges" },
  { type: "h3", text: "Processing fees and other charges" },
  { type: "p", text: "Processing fees and other charges" },
  { type: "p", text: "a) Besides interest, the Company may levy and collect fees and charges from the customer(s) for loan processing, customer care, credit assessment, ECS/ Direct Debit/ ACH/UPI mandate registration/ lodgement/ handling or for any other service provided by the Company or cost incurred by the Company related to the loan granted to the customers. These fees and charges may vary based on the asset financed, exposure limit, customer segment etc." },
  { type: "p", text: "b) Where any taxes, duties, cess are levied upon such fees and charges, same shall be recovered from the customer at applicable rates from time to time. Any such fees/ charges, or any revision therein, shall have prospective effect." },
  { type: "h3", text: "Penal Charges / late payment charges" },
  { type: "p", text: "Penal Charges / late payment charges" },
  { type: "p", text: "a) Penalty, if charged, for non-compliance of material terms and conditions of loan contract by the borrower shall be treated as ‘penal charges. These Penal charges shall also cover charges levied on the customer for delay in payment of their overdue instalment. Such penal charges would not be discriminatory in nature within particular loan or product category and be charged in proportion to the gravity of the default/breach." },
  { type: "p", text: "b) Penal charges would be reasonable and commensurate for particular loan or product category." },
  { type: "p", text: "c) It shall be ensured that such penal charges are not levied in the form of interest and are not capitalised i.e., no further interest computed on such charges. Delay in payment of penal charges will not attract any further penal charges." },
  { type: "p", text: "d) The Penal charge in case of loans sanctioned to 'individual borrowers, for purposes other than business', shall not be higher than the penal charges applicable to nonindividual borrowers for similar non-compliance of material terms and conditions. e) Any revision in these charges would be from prospective effect." },
  { type: "h3", text: "Foreclosure/ Prepayment charges" },
  { type: "p", text: "Foreclosure/ Prepayment charges" },
  { type: "p", text: "a) The Company may also levy and collect charges for prepayment/ foreclosure of loan from the customer." },
  { type: "p", text: "b) Any revision in these charges would be from prospective effect." },
  { type: "p", text: "All charges will be communicated to the customer as part of KFS." },
  { type: "h2", text: "Communication Framework" },
  { type: "p", text: "(a)  The amount of loan sanctioned along with the terms and conditions including annualized rate of interest and annualized percentage rate (inclusive of all costs and charges other than the contingent charges like penal charges and late payment charges etc.) shall be disclosed to the borrower in the key fact statement (KFS), loan agreement or any such document which is shared with the borrowers." },
  { type: "p", text: "(b)   Quantum and reason of penal charges would be clearly disclosed in bold in the loan agreement and most important terms & conditions/Key Fact Statement (KFS) as applicable, and shall not be charged to the borrower without explicit consent of the borrower." },
  { type: "p", text: "(c)  Whenever reminders for non-compliance of material terms and conditions of loan are sent to borrowers, the applicable penal charges shall be communicated through appropriate modes. Further, any instance of levy of penal charges and the reason therefor shall also be communicated" },
  { type: "p", text: "(d)  Any change in the T&Cs including disbursement schedule, interest rates, service charges, prepayment charges etc. shall be notified to the borrower and would be affected prospectively." },
  { type: "h2", text: "Top-Up and Renewal of Gold Loans" },
  { type: "p", text: "(a)  Top-up loans may be offered where sufficient LTV headroom exists based on the current Standard Gold Value." },
  { type: "p", text: "(b)  Renewal shall be permitted on formal borrower request, subject to: (i) fresh credit appraisal; (ii) full repayment of accrued interest (mandatory for Bullet/Monthly Plan loans); and (iii) adequate LTV headroom based on current gold price." },
  { type: "p", text: "(c)  Top-up and renewed loans are fresh loans for KFS, Sanction Letter, Loan Agreement, and documentation purposes. The rate applicable is the prevailing Scheme rate at the time of renewal, not the original rate." },
  { type: "p", text: "(d)  Consecutive renewals more than twice shall be flagged for enhanced credit review before further renewal is permitted." },
  { type: "h2", text: "Review of This Policy" },
  { type: "p", text: "This Policy shall be reviewed at least once per financial year, or more frequently if required due to:" },
  { type: "p", text: "Changes in applicable RBI regulations or master directions." },
  { type: "p", text: "Significant changes in the Company's business model, product mix, or technology architecture." },
  { type: "p", text: "Directions from the Board, Audit Committee, or the RBI." },
  { type: "p", text: "Amendments require Board of Directors approval. The effective date of any revision shall be recorded. A version history shall be maintained for audit and regulatory purposes." },
];
