import type { LegalBlock } from "@/components/legal-document";

export const PRIVACY_POLICY_BLOCKS = [
  { type: "title", text: "Privacy policy" },
  { type: "meta", text: "Policy version 1.0 · Approved 8 June 2026 · Approved by Board of Directors" },
  { type: "h2", text: "1. Introduction" },
  { type: "p", text: "1.1.  This Privacy Policy describes how Yellow Metal Loans Private Limited (\"Yellow Metal Loans\", \"we\", \"us\", or \"our\") collects, uses, stores, and shares your personal information when you apply for or avail a gold loan from us, visit our website, or interact with us through any channel." },
  { type: "p", text: "1.2.  We are a Reserve Bank of India (RBI)-registered Non-Banking Financial Company (NBFC) primarily engaged in providing gold loans. We take the privacy of your personal information seriously and are committed to handling it responsibly and in accordance with applicable law, including the Digital Personal Data Protection Act, 2023 (DPDP Act)." },
  { type: "p", text: "1.3.  By submitting a loan application, visiting our website, or availing any of our services, you agree to the collection and use of your information as described in this Policy. Please read it carefully." },
  { type: "p", text: "1.4.  This Policy should be read together with the Loan Agreement and the Key Facts Statement (KFS) issued to you at loan sanction." },
  { type: "h2", text: "2. What Information We Collect About You" },
  { type: "p", text: "We collect only the information that is necessary to process your loan application, complete KYC verification, manage your loan account, and comply with legal and regulatory requirements. The categories of information we collect include:" },
  { type: "h3", text: "Identity and KYC Information" },
  { type: "p", text: "Your name, date of birth, gender, photograph, address, and government-issued identification documents such as your Aadhaar card (stored in masked form -- last 4 digits only), PAN card, Voter ID, Driving Licence, or Passport. This information is collected as required under RBI KYC regulations." },
  { type: "h3", text: "Contact Information" },
  { type: "p", text: "Your mobile number, email address (if provided), and residential or correspondence address. We use this to send you the Key Facts Statement, disbursement confirmation, payment reminders, and other important loan-related notices." },
  { type: "h3", text: "Financial Information" },
  { type: "p", text: "Your bank account number and IFSC code (or UPI ID), used to disburse the loan amount to your account. We also obtain your credit report from a licensed Credit Information Company to assess your creditworthiness before sanctioning a loan." },
  { type: "h3", text: "Gold Collateral Information" },
  { type: "p", text: "Details of your pledged gold ornaments -- description, weight, purity (in carats), and photographs taken at the time of appraisal. This is used to document and safeguard the collateral in our custody." },
  { type: "h3", text: "Loan Account and Transaction Information" },
  { type: "p", text: "Details of the loan amount sanctioned, interest rate, repayment history, LTV ratio, and any outstanding dues. We use this to manage your loan account and report loan performance to licensed credit bureaus as required by law." },
  { type: "h3", text: "Device and Location Information (for Digital KYC only)" },
  { type: "p", text: "If you use Aadhaar-based offline verification (OVSE), Video-based Customer Identification (V-CIP), or any other digital KYC mode, we may collect your device information and geographic location as required by RBI guidelines for such modes. For physical branch-based loans, we do not collect device or location data." },
  { type: "h2", text: "3. How We Collect Your Information" },
  { type: "p", text: "We collect your information through the following means:" },
  { type: "p", text: "Directly from you: When you visit our branch, submit a loan application, provide KYC documents, and interact with our staff." },
  { type: "p", text: "Through our digital origination system: Our branch staff use an internal loan origination application to record your details, capture gold appraisal information, and process your loan. This application is used by our employees and is not directly accessible to you." },
  { type: "p", text: "From third-party verification sources: We receive information from government-authorised identity verification agencies (such as Aadhaar and PAN verification services) and licensed Credit Information Companies, to the extent necessary to verify your identity and assess your creditworthiness." },
  { type: "p", text: "From your bank: We verify your bank account details with your bank before disbursing the loan, to ensure the loan proceeds are credited to the correct account." },
  { type: "h2", text: "4. Why We Use Your Information" },
  { type: "p", text: "We may use your data (as mentioned above) for various things including specific business purposes (“Services”), which will include the following:" },
  { type: "p", text: "a) to provide services that might be required by the customer," },
  { type: "p", text: "b) to process the customer’s financial and non-financial transaction requests," },
  { type: "p", text: "c) to undertake research and analytics for offering or improving the Company’s services," },
  { type: "p", text: "d) to check and process the user’s application for availing any financial services," },
  { type: "p", text: "e) to share any updates/changes to the services and the terms and conditions with the user/customer," },
  { type: "p", text: "f) to take up and investigate any complaints/claims/disputes." },
  { type: "p", text: "g) to respond to queries and feedback submitted by you" },
  { type: "p", text: "h) for verification of your identity as per the internal policies including KYC." },
  { type: "p", text: "i) Undertake marketing, advertising and promotional activities to bring you products and services which may be appropriate or of interest to you. However, we do not sell or transfer your personal data to third parties for their marketing or promotional purposes, without your explicit and specific consent;" },
  { type: "p", text: "j) For business or portfolio transfers or in connection with a substantial corporate transaction, including to evaluate or conduct assignment of receivables, securitization, restructuring, reorganization, mergers and acquisitions, divestiture, sale of business all or any of our assets whether as a going concern or otherwise, including in and bankruptcy, dissolution or liquidation proceedings;" },
  { type: "p", text: "k) to fulfil the requirements of applicable laws / regulations and / or court orders / regulatory directives received by the Company." },
  { type: "p", text: "l) Otherwise with your consent." },
  { type: "h2", text: "5. Who We Share Your Information With" },
  { type: "p", text: "Yellow Metal Loans shall not disclose your personal data or information to any third party without your prior consent, except where such disclosure is agreed upon in a contract or required by law. All such third parties are obligated to maintain strict confidentiality and adhere to stringent data protection requirements to ensure your information is handled securely and in compliance with applicable privacy laws. Neither Yellow Metal Loans nor any third party shall publish or further disclose your personal data received. We ensure all disclosures comply with applicable laws and contractual obligations to protect your privacy." },
  { type: "p", text: "Where possible, you shall have the option to restrict disclosure to third parties. However, where sharing of information to a particular third party is necessary for providing the products and/or services, you shall not be able to avail such products and/or services in case you decide to restrict such disclosure." },
  { type: "p", text: "Following are the third parties to whom your information may be shared for providing/enabling the products and/or services:" },
  { type: "h3", text: "Type of Third Party" },
  { type: "h3", text: "Description" },
  { type: "p", text: "Banking partners, payment processing partners, co-branding partners, lending partner, third-party vendors, and credit information companies" },
  { type: "p", text: "We may share your information/information submitted by you to financial institutions and service providers such as payment processors, card issuers, NBFC partners and banking partners, collection service providers, credit information companies, to facilitate transactions/for providing such product and/or service." },
  { type: "p", text: "IT Service Providers" },
  { type: "p", text: "We may share your information to IT Service Providers who are engaged in the provision of information technology services for fulfilling various aspects of the Platform and for research and data analytics." },
  { type: "p", text: "Identity and other information verification providers" },
  { type: "p", text: "We may share your information to identity and other information verification to complete identification and information verification processes in accordance with applicable laws." },
  { type: "p", text: "Statutory disclosures to government and regulatory organisations" },
  { type: "p", text: "We may share your information, with or without consent, with the government, law enforcement agencies, authorities, and regulatory bodies authorized by law for identity verification, prevention, detection, investigation including cyber incidents, prosecution, or punishment of offences, provided such request for data/ information is received in writing and not further shared or published or when the Company must comply with its legal obligations. Disclosure may also be made to any third party mandated by a court or order under law for the time being in force." },
  { type: "p", text: "Marketing, business development, and sales partners" },
  { type: "p", text: "We may share your information with marketing, business development and sales partners for the purpose of improving and carrying out marketing or business development activities to provide promotional offers and better services to you." },
  { type: "p", text: "If you send us personal correspondence, such as emails or letters, or if other users or third parties send us correspondence about your activities on the Platform, we may collect and store such information for providing services and for record keeping purposes." },
  { type: "h2", text: "6. How Long We Keep Your Information" },
  { type: "p", text: "We retain your personal information for as long as your loan account is active and for a period after it is closed, as required under applicable law. In general:" },
  { type: "p", text: "KYC documents and account-opening records are retained for at least 5 years after your loan account is closed, as required under anti-money laundering regulations." },
  { type: "p", text: "Loan agreements, KFS, and transaction records are retained for at least 5 years after the date of the transaction." },
  { type: "p", text: "Gold appraisal records and gold custody documents are retained for the duration of the loan and for a reasonable period after closure." },
  { type: "p", text: "When retention periods expire, we securely delete or anonymise your personal information." },
  { type: "h2", text: "7. How We Protect Your Information" },
  { type: "p", text: "We implement appropriate security measures to protect your personal information against unauthorised access, disclosure, alteration, or loss. These include:" },
  { type: "p", text: "Access to your personal information in our systems is restricted to authorised employees who need it to perform their job." },
  { type: "p", text: "All our third-party integrations (identity verification, credit bureau, e-sign) are secured through API authentication." },
  { type: "p", text: "Physical KYC documents at our branches are stored securely and accessible only to authorised staff." },
  { type: "p", text: "In the event of a personal data breach that is likely to affect you, we will notify you and the Data Protection Board of India (DPBI) in accordance with applicable law." },
  { type: "h2", text: "8. Your Rights" },
  { type: "p", text: "Under the Digital Personal Data Protection Act, 2023, you have the following rights with respect to your personal information:" },
  { type: "p", text: "Right to Information" },
  { type: "p", text: "You can ask us what personal information we hold about you, why we hold it, and who we have shared it with. We will respond to your request within 30 days." },
  { type: "p", text: "Right to Correction and Erasure" },
  { type: "p", text: "You can ask us to correct inaccurate or incomplete personal information we hold about you. You can also ask us to delete your personal information when it is no longer needed for the purpose for which it was collected." },
  { type: "p", text: "Please note: some of your information must be retained under applicable law (such as KYC and transaction records under anti-money laundering rules). We cannot delete such information during the mandatory retention period, and we will explain this to you if you make a request." },
  { type: "p", text: "Right to Nominate" },
  { type: "p", text: "You can nominate someone to exercise your data rights on your behalf in case of your death or incapacity. Please contact our Compliance Officer to register a nominee." },
  { type: "p", text: "Right to Grievance Redressal" },
  { type: "p", text: "If you have any concern about how we handle your personal information, you can raise a complaint with our Data Protection Officer (see Section 10). If we do not resolve your concern within 30 days, you may escalate your complaint to the Data Protection Board of India (DPBI)." },
  { type: "h2", text: "9. Contact Us" },
  { type: "p", text: "The name and contact details of the Grievance Redressal Officer are provided below. You may contact the Grievance Officer to address any discrepancies and grievances you may have with respect to your personal information with the Company and the same will be redressed expeditiously." },
  { type: "h3", text: "Name" },
  { type: "p", text: "Rahul Boggaram Nagarjuna Gupta" },
  { type: "h3", text: "Designation" },
  { type: "p", text: "Nodal/ Grievance Officer, Director" },
  { type: "h3", text: "Email Address" },
  { type: "p", text: "contact@yellowmetal.co" },
  { type: "h3", text: "Phone Number" },
  { type: "p", text: "9090976076" },
  { type: "h3", text: "Office Address" },
  { type: "p", text: "Ground Floor, Building No. 1, Nisarga, 1st Main, 3rd Cross, Opp. Deccan Hospital, Ashwini Extension, Chintamani, Chikkaballapur, Karnataka - 563125" },
  { type: "h2", text: "11. Updates to This Policy" },
  { type: "p", text: "We may update this Privacy Policy from time to time to reflect changes in our services, applicable law, or how we handle your information. When we make material changes, we will update the Last Updated date at the top of this document and notify you by SMS or WhatsApp to your registered mobile number. We encourage you to review this Policy periodically." },
] as const satisfies readonly LegalBlock[];
