import type { LegalBlock } from "@/components/legal-document";

export const TERMS_AND_CONDITIONS_BLOCKS = [
  { type: "title", text: "Terms & conditions" },
  { type: "subtitle", text: "Terms and Conditions for Use of the Website" },
  { type: "meta", text: "Last updated: June 2026" },
  { type: "p", text: "Yellow Metal Loans Private Limited is a Non-Banking Financial Company (NBFC) registered with and regulated by the Reserve Bank of India (\"RBI\"), incorporated under the Companies Act, 2013, engaged in providing gold loan facilities (hereinafter referred to as \"Company\", \"We\", \"Us\" or \"Our\"). These Terms and Conditions (\"Terms\") govern the access to and use of the Company's website, www.yellowmetal.co (\"Website\"), by any person accessing the Website (\"User\", \"You\" or \"Your\")." },
  { type: "p", text: "PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY BEFORE ACCESSING OR USING THIS WEBSITE. THIS IS A LEGALLY BINDING AGREEMENT BETWEEN YOU AND THE COMPANY." },
  { type: "p", text: "BY ACCESSING OR USING THIS WEBSITE OR ANY PAGES THEREOF, YOU AGREE TO BE BOUND BY THESE TERMS AND CONDITIONS AND THE COMPANY'S PRIVACY POLICY. IF THESE TERMS ARE NOT ACCEPTABLE TO YOU, PLEASE DO NOT ACCESS OR USE THIS WEBSITE." },
  { type: "p", text: "Headings in these Terms are for convenience only and do not affect interpretation. Please read these Terms in full." },
  { type: "h2", text: "I. General" },
  { type: "p", text: "These Terms set forth the conditions applicable to use of this Website by a User. The Terms are governed by applicable Indian laws, including but not limited to:" },
  { type: "p", text: "The Indian Contract Act, 1872;" },
  { type: "p", text: "The Information Technology Act, 2000 (\"IT Act\");" },
  { type: "p", text: "The Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011; and" },
  { type: "p", text: "The Digital Personal Data Protection Act, 2023 and rules framed thereunder, as amended from time to time." },
  { type: "p", text: "These Terms, being electronically generated, constitute an electronic record within the meaning of the IT Act and do not require a physical or digital signature." },
  { type: "h2", text: "II. Nature of the Website" },
  { type: "p", text: "This Website is maintained solely for informational purposes. It provides general information about the Company, its gold loan products and services, regulatory disclosures, grievance redressal mechanisms, and contact details. The Website is not a customer sourcing platform. Specifically:" },
  { type: "p", text: "No loan application, credit assessment, or loan disbursal is conducted through this Website." },
  { type: "p", text: "Visiting or using this Website does not constitute an application for, or offer of, any credit facility." },
  { type: "p", text: "The Company does not source customers or solicit loan business through this Website." },
  { type: "p", text: "Any actual gold loan facility extended by the Company is governed by a separate loan agreement, Key Facts Statement (KFS), and such other documents as executed between the Company and the borrower at the Company's branch." },
  { type: "p", text: "Information on indicative interest rates, charges, or loan-to-value ratios, if published on this Website, is for general awareness only and is subject to change without notice. Applicable rates and terms are determined at the time of loan execution at the branch level." },
  { type: "h2", text: "III. User Representation" },
  { type: "p", text: "By accessing this Website, You represent and warrant that:" },
  { type: "p", text: "You are a natural person who has attained the age of 18 years or a legally constituted entity;" },
  { type: "p", text: "You are legally permitted to access websites and use information under applicable Indian laws;" },
  { type: "p", text: "Any information You provide to the Company (through contact forms or correspondence) is accurate, complete, and not misleading; and" },
  { type: "p", text: "You will use the Website only for lawful purposes and in accordance with these Terms." },
  { type: "p", text: "If You violate any of these Terms, the Company reserves the right to restrict or terminate Your access to the Website at any time, with or without notice." },
  { type: "h2", text: "IV. Compliance with Terms" },
  { type: "p", text: "Your right to access and use this Website is personal and non-transferable. You are responsible for ensuring that Your use of the Website complies fully with applicable laws and these Terms. The Company reserves the right to deny access to the Website to any User found to be in breach of these Terms or applicable law." },
  { type: "h2", text: "V. Grant of Licence" },
  { type: "p", text: "The Company grants You a limited, non-exclusive, non-transferable licence to access and browse this Website for personal, non-commercial informational purposes only. This licence does not permit:" },
  { type: "p", text: "Downloading or copying any material from the Website (other than temporary page caching by a standard browser), except with the prior written consent of the Company;" },
  { type: "p", text: "Any commercial use, redistribution, reproduction, or exploitation of the Website or its contents;" },
  { type: "p", text: "Modifying, reverse-engineering, decompiling, or disassembling any part of the Website;" },
  { type: "p", text: "Framing or mirroring any page of the Website; or" },
  { type: "p", text: "Using data mining, robots, scrapers, or similar automated tools to extract content from the Website." },
  { type: "p", text: "Any unauthorised use of this Website will automatically terminate the licence granted by the Company." },
  { type: "h2", text: "VI. Amendment of Terms" },
  { type: "p", text: "The Company reserves the right to amend, modify, or update these Terms at any time without prior notice. Amendments take effect immediately upon publication on the Website. Your continued use of the Website following any such change constitutes Your acceptance of the revised Terms. You are advised to review these Terms periodically." },
  { type: "h2", text: "VII. Use of Content and Information" },
  { type: "p", text: "All content on this Website, including text, graphics, logos, data, and links (\"Content\"), is provided for general information purposes only and does not constitute financial, legal, or investment advice. You should not act or refrain from acting on the basis of Content on this Website without seeking independent professional advice appropriate to Your circumstances." },
  { type: "p", text: "The Content is protected by applicable copyright and intellectual property laws. You may not reproduce, publish, distribute, or commercially exploit any Content without the prior written permission of the Company." },
  { type: "h2", text: "VIII. Intellectual Property Rights" },
  { type: "p", text: "The name \"Yellow Metal Loans\", its logo, trademark, and all rights in and to the Website, including but not limited to copyrights, trademarks, trade dress, source code, and all other intellectual property rights, vest exclusively in the Company. Nothing in these Terms shall be construed as granting any licence or right to use any intellectual property of the Company other than as expressly provided herein." },
  { type: "h2", text: "IX. Monitoring of Website Use" },
  { type: "p", text: "The Company reserves the right to monitor access to and use of the Website at all times to ensure compliance with these Terms, applicable law, and to safeguard the integrity and security of the Website. The Company may share information with governmental authorities as required by applicable law." },
  { type: "h2", text: "X. Privacy Policy" },
  { type: "p", text: "Any personal information shared by You with the Company through this Website is governed in accordance with the Company's Privacy Policy, available at www.yellowmetal.co/privacy-policy. Please read the Privacy Policy carefully before sharing any personal information." },
  { type: "h2", text: "XI. Restrictions on Use" },
  { type: "p", text: "While accessing or using this Website, You agree that You shall not:" },
  { type: "p", text: "Infringe the Company's or any third party's intellectual property rights, rights of publicity, or privacy;" },
  { type: "p", text: "Post, transmit, or publish any message, image, or content that violates any applicable law or infringes the rights of any third party;" },
  { type: "p", text: "Remove, disable, or circumvent any security features or access controls on the Website;" },
  { type: "p", text: "Upload or introduce any virus, malware, or harmful code that could affect the functionality of the Website or any connected system;" },
  { type: "p", text: "Attempt to gain unauthorised access to the Website, its servers, or any connected network;" },
  { type: "p", text: "Overburden, disrupt, or impair the Website or its infrastructure;" },
  { type: "p", text: "Provide false, inaccurate, or misleading information in any communication with the Company; or" },
  { type: "p", text: "Use the Website for any illegal, fraudulent, or prohibited purpose." },
  { type: "h2", text: "XII. Third-Party Websites and Links" },
  { type: "p", text: "This Website may contain hyperlinks to external websites operated by third parties, including regulatory bodies, government portals, or other institutions. Such links are provided for convenience only. The Company does not endorse, verify, or assume any responsibility for the content, accuracy, security, or availability of any third-party website. Your access to and use of any linked third-party website is at Your own risk and subject to that website's own terms." },
  { type: "h2", text: "XIII. Disclaimers" },
  { type: "p", text: "To the fullest extent permitted by applicable law, this Website and all Content thereon is provided on an \"as is\" and \"as available\" basis without any representation or warranty, express or implied, including without limitation warranties of merchantability, fitness for a particular purpose, accuracy, completeness, or non-infringement." },
  { type: "p", text: "The Company does not warrant that:" },
  { type: "p", text: "The Website will be continuously available, uninterrupted, or error-free;" },
  { type: "p", text: "Defects or errors will be corrected; or" },
  { type: "p", text: "The Website or its servers are free from viruses or harmful components." },
  { type: "p", text: "Use of the Website and reliance on any Content thereon is entirely at Your own risk. The Company expressly disclaims all liability for any loss or damage arising from Your use of, or inability to use, this Website or its Content." },
  { type: "h2", text: "XIV. Grievance Redressal" },
  { type: "p", text: "In the event of any grievance arising from Your use of this Website, You may contact the Company's Nodal / Grievance Officer at: contact@yellowmetal.co or at the address specified in the Company's Grievance Redressal Policy available on this Website." },
  { type: "p", text: "For any grievance relating to a gold loan facility extended by the Company, the separate grievance redressal mechanism under the Company's Fair Practices Code and RBI's grievance framework shall apply." },
  { type: "h2", text: "XV. Indemnity and Limitation of Liability" },
  { type: "p", text: "You agree to indemnify, defend, and hold harmless the Company and its directors, officers, employees, agents, and affiliates from and against any and all claims, liabilities, losses, damages, costs, and expenses (including reasonable legal fees) arising out of or relating to: (a) Your use or misuse of this Website; (b) Your violation of these Terms; or (c) Your infringement of any intellectual property or other rights of any third party." },
  { type: "p", text: "To the maximum extent permitted by applicable law, the Company and its directors, officers, employees, and agents shall not be liable for any direct, indirect, incidental, consequential, special, or punitive damages whatsoever arising from or in connection with Your use of, or inability to use, this Website." },
  { type: "h2", text: "XVI. Governing Law and Jurisdiction" },
  { type: "p", text: "These Terms shall be governed by and construed in accordance with the laws of India. The courts at Chikkaballapur, Karnataka shall have exclusive jurisdiction over any dispute arising out of or in connection with these Terms or Your use of this Website." },
] as const satisfies readonly LegalBlock[];
